FROM python:3.11-slim

WORKDIR /app

# Copia i requirements e installa dipendenze
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia il resto del codice
COPY . .

# Avvia l'app
CMD ["python", "app.py"]