name: CI/CD to AWS ECS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout codice
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Configura credenziali AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 5️⃣ Login su ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # 6️⃣ Build immagine Docker
      - name: Build Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          docker build -t ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG .
          docker tag ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION 
}}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG

      # 7️⃣ Push immagine su ECR
      - name: Push Docker image to ECR
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ 
secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY 
}}:$IMAGE_TAG

      # 8️⃣ Aggiorna ECS Service
      - name: Update ECS service
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER }} \
            --service ${{ secrets.ECS_SERVICE }} \
            --force-new-deployment \
            --image ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ 
secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY 
}}:$IMAGE_TAG
